### ISSUE TITLE
Selfie Segmentation?

### ISSUE THREAD

**Issue by arianaa30** [google-ai-edge/mediapipe-samples#222]
Can we use Mediapipe for selfie segmentation on Android? I couldn't find any examples.

**Comment by PaulTR** [comment]
Yes :) It's under the segmentation category mask example. In the bottom sheet there's a model selector that you can use to pick the selfie segmentation model. https://github.com/googlesamples/mediapipe/tree/main/examples/image_segmentation/android/category_mask

**Comment by arianaa30** [comment]
Cool. Is it good enough for live video?
Like, how different would it be than MLKit's selfie segmentation? https://developers.google.com/ml-kit/vision/selfie-segmentation

**Comment by PaulTR** [comment]
Well the sample is using it for live video :)

I haven't used MLKIt's version in a long time, but I'd imagine comparable. You'd have to try it out to see if it does what you'd need.

**Comment by arianaa30** [comment]
Got it thanks. Btw do we have a Java version of the code you sent as well? (not kotlin)

**Comment by PaulTR** [comment]
Nope, but it should be easy enough to write in Java - the structures are really simplified. Personally though, if you're doing Android development you should really check out Kotlin :) You can write entire classes in it and plug them into mostly Java codebases, too.

**Comment by arianaa30** [comment]
Yeah I think I should start learning Kotlin! Makes it concise
