### ISSUE TITLE
Android gesture detection. 

### ISSUE THREAD

**Issue by ghost** [google-ai-edge/mediapipe-samples#281]
How can I add more categories/gestures to the model?
also, I have a problem the landmarks doesn't appear exactly in my hand...
![Screenshot_20231121_223140](https://github.com/googlesamples/mediapipe/assets/131215231/64e08a5c-0c50-49a9-b5b3-809e1f5ce704)
![Screenshot_20231121_223246](https://github.com/googlesamples/mediapipe/assets/131215231/c16baebf-eca3-45d2-ac31-eebe7b7534e8)

**Comment by PaulTR** [comment]
Hey @Rawabi20 what device are you using? That looks like a UI bug (though maybe the left/right settings could be contributing to it, so I'll investigate that too). Basically the way the sample works is an image is taken from the camera, resized, inference is run, then the points for that resized image are sent back as a result to be rescaled and displayed.
