### ISSUE TITLE
Android Object Detection ResultListener get Current Bitmap from MPImage

### ISSUE THREAD

**Issue by AnyLifeZLB** [google-ai-edge/mediapipe-samples#282]
As the samples code 

setResultListener(this::returnLivestreamResult)

![image](https://github.com/googlesamples/mediapipe/assets/15169396/2522b4da-e705-423a-b942-ff1b33b0b8d6)

How can I get Current Bitmap from MPImage? 

thank you .

**Comment by ArtanBerisha1** [comment]
You should use extract() method from BitmapExtractor class that mediapipe provides, e.g:
val bitmap = BitmapExtractor.extract(result.generatedImage())
