### ISSUE TITLE
can't build iOS examples with Xcode 15.1

### ISSUE THREAD

**Issue by kriddile** [google-ai-edge/mediapipe-samples#305]
I've tried to build both the FaceLandmarker and FaceDetector iOS examples with Xcode 15.1 using [the provided instructions](https://developers.google.com/mediapipe/solutions/setup_ios#example_code):

1. clone the repo
2. run `pod install` from the project directory
3. open the generated .xcworkspace in Xcode
4. attempt to build the appropriate scheme

With those two example apps, the build always fails with `No such module 'MediaPipeTasksVision'`.

**Comment by Stardusted1** [comment]
Same error

**Comment by blayer** [comment]
same error for `MediaPipeTasksGenAI`, but I was able to build under a self created project after `pod install`.

**Comment by PaulTR** [comment]
What was the full error message you get? I just ran with 15.1 on a new project import and needed to do `pod repo update` because it was listed in the error message, then `pod install` worked.
