### ISSUE TITLE
'ERROR: Unable to read from webcam. Please verify your webcam settings.'

### ISSUE THREAD

**Issue by EGCVants** [google-ai-edge/mediapipe-samples#383]
I would appreciate if anyone could provide assistance regarding this error message. Mediapipe has been installed and the camera being used with the Raspberry Pi 4 is functioning, which was verified by using the following command to test it. 

libcamera-still -o test.jpg

The issue however occurs when attempting to run the recognize.py script, which gives me the error:
 "ERROR: Unable to read from webcam. Please verify your webcam settings."

 I'm unsure if the issue is coming from the use of cv2 and the introduction of the new python library PiCamera2 or something else entirely. The following code seems to be where the error is occurring, but I just don't how to resolve it. Again, I'd greatly appreciated the help if possible.

# Continuously capture images from the camera and run inference
 while cap.isOpened():
    success, image = cap.read()
    if not success:
      sys.exit(
          'ERROR: Unable to read from webcam. Please verify your webcam settings.'
      )
Lines(100-106)

where cap seems to instantiated below as cv2:
# Start capturing video input from the camera
  cap = cv2.VideoCapture(camera_id)
  cap.set(cv2.CAP_PROP_FRAME_WIDTH, width)
  cap.set(cv2.CAP_PROP_FRAME_HEIGHT, height)

Lines(56-59)

**Comment by PaulTR** [comment]
Apparently it's an issue with a newer version of the camera. Someone sent
me a workaround they used, I just haven't had time to look into it with
being on leave and IO. I'll dig up their code when I'm back at work on
Tuesday to post.

**Comment by EGCVants** [comment]
Thank you very much. Said it a lot, but it is greatly appreciated

**Comment by PaulTR** [comment]
Alright maybe this will help :) https://gist.github.com/jeffehobbs/d9cbe007c94517cb758dd5e69413cfd6

**Comment by lianneStrik** [comment]
where do you have to add this? i'm stuck on the same thing but don't know how to fix it
