### ISSUE TITLE
Issues for a change of trained model

### ISSUE THREAD

**Issue by furia-Bellett** [google-ai-edge/mediapipe-samples#396]
Hi, I wanted to ask for help: 

I'm using your gesture_recognize code for one of my school projects, 
I trained my artificial intelligence with my customized gestures and once I inserted model.task in the assets folder and changed the path of the model in the gestureRecognizeHelper file it gives me the error "Gesture recognizer failed to initialize. See error logs for " + "details" (line 98 of the same file) 
how can I solve it?

**Comment by PaulTR** [comment]
Can you post the error logs for details? :)

**Comment by PaulTR** [comment]
Closing out due to non-response
