### ISSUE TITLE
Gesture Recognizer example with Raspberry Pi performance issues

### ISSUE THREAD

**Issue by vincedani** [google-ai-edge/mediapipe-samples#404]
Hello 👋,

I am trying out the Raspberry Pi example from the Gesture Recognition example, following its readme. However, it's working with around 4 FPS and the latency of the drawing is very high.

```bash
$ cat /sys/firmware/devicetree/base/model
Raspberry Pi 3 Model B Rev 1.2
```

```bash
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
```

Is it the desired behavior of the app, or am I missing some additional configuration step? Shall I change the device to a newer one?

**Comment by PaulTR** [comment]
So my first guess is that it's just because it's on a 3B - I did all of my testing on a 4B and had ok results (in the grand scheme of things; it is running on a Pi :P But I saw around 5-9 fps).

**Comment by vincedani** [comment]
Thank you @PaulTR for the information, then simply changing the device won't do the magic.

I have got the information, closing the issue.
