### ISSUE TITLE
Can mediapipe-models  be used for free for commercial purposes ?

### ISSUE THREAD

**Issue by zw0241** [google-ai-edge/mediapipe-samples#407]
Can the models in 'https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task'   be used for free for commercial purposes?

**Comment by PaulTR** [comment]
Yup! The underlying models are all apache 2.0 licensed. https://storage.googleapis.com/mediapipe-assets/MediaPipe%20BlazeFace%20Model%20Card%20(Short%20Range).pdf
