### ISSUE TITLE
LLM Models other than Gemma , falcon, phi, stablelm

### ISSUE THREAD

**Issue by Nikhil34712** [google-ai-edge/mediapipe-samples#410]
Can we use other llm other than Gemma, falcon, phi, stablelm cause when i add other model in llm_conversion notebook its showing error to choosw only 4 of them what ro do can anyone explain ??

**Comment by PaulTR** [comment]
The four are set up for that conversion script, but if you want to do anything else/custom, then you'll need to use the [AI Edge Torch Generative API ](https://developers.googleblog.com/en/ai-edge-torch-generative-api-for-custom-llms-on-device/)
