### ISSUE TITLE
Gemma-1.1-2B-it-cpu-int4.bin generating junk response in phone.

### ISSUE THREAD

**Issue by gagangayari** [google-ai-edge/mediapipe-samples#414]
I have been trying llm_inference on android (https://github.com/google-ai-edge/mediapipe-samples/tree/main/examples/llm_inference/android). While the model performs perfectly in the emulator, it starts generating junk outputs when I run it on an actual phone.

![mediapipe-error](https://github.com/google-ai-edge/mediapipe-samples/assets/55296443/97efac86-b0c8-49d0-a0e5-5908f5dbeb5a)

The model is downloaded from https://www.kaggle.com/models/google/gemma/tfLite/ , as provided in the docs.

Phone Configurations 
Android version : 13
RAM : 6GB
Model : Samsung A23

**Comment by jggomez** [comment]
I got the same result

is there any response?

**Comment by PaulTR** [comment]
![Screenshot_20240704-135341](https://github.com/google-ai-edge/mediapipe-samples/assets/2335087/382929e1-035d-484c-8b00-2ad09380c3c0)

Alright I ran through this as a fresh sample and model download (model_path = /data/local/tmp/llm/gemma-2b-it-gpu-int4.bin) and couldn't replicate it, but I'll log it internally to see if anyone else is able to replicate it.

**Comment by ACorsicanGuy** [comment]
you did it with the gpu model, not the cpu
i got the same problem

**Comment by android-sg** [comment]
Faced the same, switching to gpu model from cpu model worked for me. Trying using gpu model instead.

**Comment by shubham0204** [comment]
After switching to the `gemma-1.1-2b-it-gpu-int4` model to get a cleaner reply, I got the following error on initializing the inference session: 

`com.google.mediapipe.framework.MediaPipeException: internal: Failed to initialize session: %sCan not open OpenCL library on this device - undefined symbol: clSetPerfHintQCOM`

**Comment by PaulTR** [comment]
A new version of MediaPipe recently went out which should hopefully fix this issue as well.
