### ISSUE TITLE
Unable to detect hand pose estimation for Android live app

### ISSUE THREAD

**Issue by IBSApple** [google-ai-edge/mediapipe-samples#425]
Hello Mediapipe,

           I want to integrated Mediapipe Hand Pose estimation for my live app but it's showing me below error in release apk.

          **Hand Landmarker failed to initialize. See error logs for details**

           But this same working for local, How to resolve this issue?

**Comment by PaulTR** [comment]
I would need to see the error logs that you mentioned to have an idea of what's going on.
