### ISSUE TITLE
[Need Support]No example of object tracking were found

### ISSUE THREAD

**Issue by tisaud** [google-ai-edge/mediapipe-samples#429]
I want example of object tracking，but i only find object detection，can you help me？（platform for android：The effect in the GIF on the right）
![mediapipe](https://github.com/user-attachments/assets/d9fdb891-c775-4b9c-86dd-33efc93fbb58)

**Comment by PaulTR** [comment]
Object tracking isn't supported out of the box with MediaPipe Tasks, but I have a feature request in.
