### ISSUE TITLE
Use local model file but have an error "Not allowed to load local resource: file:///D:/model/gemma-2b-it-gpu-int4.bin"

### ISSUE THREAD

**Issue by akau16** [google-ai-edge/mediapipe-samples#441]
When I run the llm_inference in localhost, it's ok to access model file like "gemma-2b-it-gpu-int4.bin" that is in project folder, but when I run llm_inference in Firebase Hosting, it can not access on-device's model file, it will show "Not allowed to load local resource: file:///D:/model/gemma-2b-it-gpu-int4.bin".
And I query it to get that info 'In standard HTML and JavaScript, it is not possible to directly specify to read files with a specific path on the local machine. This is due to browser security restrictions designed to protect user privacy and prevent malicious websites from automatically accessing the local file system'.

But I try your sample in MediaPipe Studio(https://mediapipe-studio.webapps.google.com/studio/demo/llm_inference), I can click 'Choose a model file' and select model file in my device and run OK, I would like to ask how can it do that? Thank you!

**Comment by schmidt-sebastian** [comment]
There are two ways to load models in our browser API:

- Load the model from a URL
If you are using this (which is what `file:///` does), you need to serve the file via Firebase Hosting as well and load the model from "localhost"

- Load the model from a File dialog
You can obtain a ReadableStreamDefaultReader from `<input type=file ...>` and pass this to our Inference API:  https://github.com/google-ai-edge/mediapipe/blob/master/mediapipe/tasks/web/core/task_runner_options.d.ts#L31

```
const fileInput = document.querySelector('input[type="file"]');

fileInput.addEventListener('change', (event) => {
  const file = event.target.files[0];
  const reader = new FileReader();
  const stream = reader.readAsArrayBuffer(file); 
  llmOptions.baseOptions.modelAssetBuffer =  stream.getReader();
...
})
