### ISSUE TITLE
In the hand_landmarker of the Android example in mediapipe-samples, the results of obtaining the handedness of the left and right hands are reversed.

### ISSUE THREAD

**Issue by jianking123** [google-ai-edge/mediapipe-samples#450]
In mediapipe-samples for Android, the results of getting handedness are reversed for the left and right hands.

**Comment by jianking123** [comment]
There was no problem when tasksVision was 0.10.0, but this problem occurred when it was upgraded to 0.10.15

**Comment by PaulTR** [comment]
You might actually be seeing the correct behavior - it was reversed in the older version. If you're using the front facing camera, the image is mirrored, so the frame that goes into the model ends up making it look like the left hand is actually the right. If you try this with the back camera, do you also see reversed results?

**Comment by jianking123** [comment]
> You might actually be seeing the correct behavior - it was reversed in the older version. If you're using the front facing camera, the image is mirrored, so the frame that goes into the model ends up making it look like the left hand is actually the right. If you try this with the back camera, do you also see reversed results?

Thanks for your reply! When using the rear camera, I commented out "postScale(
-1f, 1f, imageProxy.width.toFloat(), imageProxy.height.toFloat()
)", and the result was correct, but in my business I need to use the front camera, how should I modify the code to let the model return the correct handedness and the correct coordinates and the correct drawing
