### ISSUE TITLE
Unable to convert Qwen2.5 to mediapipe supported format

### ISSUE THREAD

**Issue by atultiwari** [google-ai-edge/mediapipe-samples#468]
I used [AI-Edge-Torch](https://github.com/google-ai-edge/ai-edge-torch.git) to convert `Qwen/Qwen2.5-0.5B-Instruct` from Huggingface to `tflite`, but as decribed in the [documentation](https://ai.google.dev/edge/mediapipe/solutions/genai/llm_inference#ai_edge_model_conversion), I am unable to proceed to the next step. As per documentation -
1. LLM mapped to a TFLite model through AI Edge - Done & created a file named `qwen_0_5b_q8_seq1024_ekv1280.tflite`
2. Create a Task Bundle - I am facing issues here.

The second step provides the following sample code snippet -
`import mediapipe as mp
from mediapipe.tasks.python.genai import bundler

config = bundler.BundleConfig(
    tflite_model=TFLITE_MODEL,
    tokenizer_model=TOKENIZER_MODEL,
    start_token=START_TOKEN,
    stop_tokens=STOP_TOKENS,
    output_filename=OUTPUT_FILENAME,
    enable_bytes_to_unicode_mapping=ENABLE_BYTES_TO_UNICODE_MAPPING,
)
bundler.create_bundle(config)`

But the problem is - [Qwen2.5](https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/tree/main) doesn't provide Tokenizer model file. How can I make it?
I also wanted to know if I need to put the output file name something like `qwen.task`. If yes then what would be the next step, it's also unclear to me.

One last question - Can Qwen2.5 (and similarly other models like Llama 3.2) can be converted to mediapipe format without using ai-edge-torch?

Thank you.
Regards
Atul

**Comment by PaulTR** [comment]
Hi @atultiwari, can you please post this to https://github.com/google-ai-edge/ai-edge-torch? Since this is an issue with the converter, it's out of the end-interpreter scope, so you'll have a lot better luck there. Thanks!
