### ISSUE TITLE
Pose Recognition Android Crashes on Startup

### ISSUE THREAD

**Issue by JKelly423** [google-ai-edge/mediapipe-samples#470]
Following [this guide here](https://ai.google.dev/edge/mediapipe/solutions/vision/pose_landmarker/android).

Build is successful, however on launching the pose recognition app via the emulator, the app instantly crashes.

Running on Android API 34 on Android 14.0 ("UpsideDownCake"). Using emulator via Android Studio.

Has anyone else ran into this issue before?

**Comment by PaulTR** [comment]
I think it's been brought up a few times here on GitHub. For some of the vision tasks you absolutely need to run on a physical device.

**Comment by JKelly423** [comment]
> I think it's been brought up a few times here on GitHub. For some of the vision tasks you absolutely need to run on a physical device.

Yes this is solved. Needs to be ran on ARM64. M1 mac's can emulate it but if running windows you need a physical device. 

I'll close this.
