### ISSUE TITLE
MediaPipe LLM Inference Demo Of Android: Error When Loading "gemma2-2b-it-cpu-int8"

### ISSUE THREAD

**Issue by baotonghe** [google-ai-edge/mediapipe-samples#474]
https://github.com/google-ai-edge/mediapipe-samples/blob/main/examples/llm_inference/android/README.md

As the wiki show, I run the sample app, firstly when I load gemma2-2b-it-gpu-int8, all thing is ok, and can inference using GPU correctly.

However when I load gemma2-2b-it-cpu-int8, it output the follow error:

![MediaPip](https://github.com/user-attachments/assets/9f191a93-9032-458e-8959-7e3f3bf975ef)

The MediaPipe app output the error log:

> --------- beginning of main
11-11 11:32:15.870 10391 10391 I es.llminference: Late-enabling -Xcheck:jni
11-11 11:32:15.964 10391 10391 I es.llminference: Using CollectorTypeCC GC.
--------- beginning of kernel
11-11 11:32:16.024 10391 10391 I binder  : 10391:10391 ioctl 40046210 7fec962450 returned -22
11-11 11:32:16.046 10391 10391 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10169; state: ENABLED
11-11 11:32:16.073 10391 10391 W ziparchive: Unable to open '/data/app/~~MbR0uikdxylkKA4NcM0W4w==/com.google.mediapipe.examples.llminference-b9shwoSGqSoojiz-JmPe-A==/base.dm': No such file or directory
11-11 11:32:16.073 10391 10391 W ziparchive: Unable to open '/data/app/~~MbR0uikdxylkKA4NcM0W4w==/com.google.mediapipe.examples.llminference-b9shwoSGqSoojiz-JmPe-A==/base.dm': No such file or directory
11-11 11:32:16.889 10391 10391 D nativeloader: Configuring classloader-namespace for other apk /data/app/~~MbR0uikdxylkKA4NcM0W4w==/com.google.mediapipe.examples.llminference-b9shwoSGqSoojiz-JmPe-A==/base.apk. target_sdk_version=34, uses_libraries=libOpenCL.so, library_path=/data/app/~~MbR0uikdxylkKA4NcM0W4w==/com.google.mediapipe.examples.llminference-b9shwoSGqSoojiz-JmPe-A==/lib/arm64:/data/app/~~MbR0uikdxylkKA4NcM0W4w==/com.google.mediapipe.examples.llminference-b9shwoSGqSoojiz-JmPe-A==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/com.google.mediapipe.examples.llminference
11-11 11:32:16.917 10391 10391 I Perf    : Connecting to perf service.
11-11 11:32:16.926 10391 10391 V GraphicsEnvironment: ANGLE Developer option for 'com.google.mediapipe.examples.llminference' set to: 'default'
11-11 11:32:16.927 10391 10391 V GraphicsEnvironment: ANGLE GameManagerService for com.google.mediapipe.examples.llminference: false
11-11 11:32:16.927 10391 10391 V GraphicsEnvironment: Updatable production driver is not supported on the device.
11-11 11:32:16.932 10391 10391 D NetworkSecurityConfig: No Network Security Config specified, using platform default
11-11 11:32:16.933 10391 10391 D NetworkSecurityConfig: No Network Security Config specified, using platform default
11-11 11:32:22.059 10391 10423 D ProfileInstaller: Installing profile for com.google.mediapipe.examples.llminference
11-11 11:38:30.976 10391 10391 D CompatibilityChangeReporter: Compat change id reported: 237531167; UID 10169; state: DISABLED
11-11 11:38:30.986 10391 10837 W Parcel  : Expecting binder but got null!
11-11 11:38:31.255 10391 10391 W es.llminference: Method boolean androidx.compose.runtime.snapshots.SnapshotStateList.conditionalUpdate(boolean, kotlin.jvm.functions.Function1) failed lock verification and will run slower.
11-11 11:38:31.255 10391 10391 W es.llminference: Common causes for lock verification issues are non-optimized dex code
11-11 11:38:31.255 10391 10391 W es.llminference: and incorrect proguard optimizations.
11-11 11:38:31.255 10391 10391 W es.llminference: Method boolean androidx.compose.runtime.snapshots.SnapshotStateList.conditionalUpdate$default(androidx.compose.runtime.snapshots.SnapshotStateList, boolean, kotlin.jvm.functions.Function1, int, java.lang.Object) failed lock verification and will run slower.
11-11 11:38:31.255 10391 10391 W es.llminference: Method java.lang.Object androidx.compose.runtime.snapshots.SnapshotStateList.mutate(kotlin.jvm.functions.Function1) failed lock verification and will run slower.
11-11 11:38:31.255 10391 10391 W es.llminference: Method void androidx.compose.runtime.snapshots.SnapshotStateList.update(boolean, kotlin.jvm.functions.Function1) failed lock verification and will run slower.
11-11 11:38:31.255 10391 10391 W es.llminference: Method void androidx.compose.runtime.snapshots.SnapshotStateList.update$default(androidx.compose.runtime.snapshots.SnapshotStateList, boolean, kotlin.jvm.functions.Function1, int, java.lang.Object) failed lock verification and will run slower.
11-11 11:38:31.295 10391 10837 I AdrenoGLES-0: QUALCOMM build                   : a3cdec2236, Ief33eea0db
11-11 11:38:31.295 10391 10837 I AdrenoGLES-0: Build Date                       : 08/23/22
11-11 11:38:31.295 10391 10837 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.35.01.12
11-11 11:38:31.295 10391 10837 I AdrenoGLES-0: Local Branch                     : 
11-11 11:38:31.295 10391 10837 I AdrenoGLES-0: Remote Branch                    : 
11-11 11:38:31.295 10391 10837 I AdrenoGLES-0: Remote Branch                    : 
11-11 11:38:31.295 10391 10837 I AdrenoGLES-0: Reconstruct Branch               : 
11-11 11:38:31.296 10391 10837 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
11-11 11:38:31.296 10391 10837 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
11-11 11:38:31.300 10391 10837 I AdrenoGLES-0: PFP: 0x016dc094, ME: 0x00000000
11-11 11:38:31.318 10391 10837 E OpenGLRenderer: Unable to match the desired swap behavior.
11-11 11:38:31.398 10391 10846 E tflite  : Model provided has model identifier 'PK', should be 'TFL3'
11-11 11:38:31.398 10391 10846 E tflite  : Model provided has model identifier 'PK', should be 'TFL3'

**Comment by talumbau** [comment]
Hi,

Did you download the file and keep the `.task` file extension? The GPU model has a `.bin` extension while the CPU model has a `.task` extension. This is currently how we differentiate the difference pipelines for running the model. I have not seen this error when using the latest MP release and the `.task` file for the model resource. Please confirm you are doing both of those things. Thanks!

**Comment by baotonghe** [comment]
> Hi,
> 
> Did you download the file and keep the `.task` file extension? The GPU model has a `.bin` extension while the CPU model has a `.task` extension. This is currently how we differentiate the difference pipelines for running the model. I have not seen this error when using the latest MP release and the `.task` file for the model resource. Please confirm you are doing both of those things. Thanks!

@talumbau sorry, I made a mistake, I shouldn't have changed the suffix, I will try It, thank you.
